# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590a7c0a679c351e3c8dbb7ce653a4c03e434f6884af7f926ffd56e401bb266d9fc63baf77441b8f6832446fc161ede361b3e474d3ab2dc268627b4a5f34144b

test:
  secret_key_base: d40bc187f1edc1a8b5ae0d0299699ff78727df82c81b1d5c726594641ee56a2f6a1d06813ad25360c089eda1d4761221ad7045ddb91b0cd16722480722d6b1a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
